# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Build

on:
- push

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        node:
        - 22

      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Install Yarn
      run: npm install --global yarn

    - name: Install Dependencies
      run: yarn install

    - name: Test to generate list dynamically
      run: node dynamic-list.js

    - name: Test of sign and seal section of contract
      run: node contract-sign-and-seal-section.js
